### PR TITLE
fix ngrok postinstall.js error

### PR DESCRIPTION
**Pull request by aMoniker**
This was happening during `grunt init`

### CODE REVIEW

**Comment by fiznool** [comment]
Thanks for submitting this. Looks like this is also [tracked in the upstream repo](https://github.com/bubenshchykov/ngrok/issues/35).

As I'm on Linux, I'm not seeing this error. Are you using a Mac?

Unfortunately upgrading to ngrok 2.0 breaks the ability to listen for a webhook trigger due to [this upstream issue](https://github.com/bubenshchykov/ngrok/issues/34). We'll need to wait for that to be resolved before merging this in.

**Comment by johnmjackson** [comment]
FYI, I'm using a Mac and haven't seen this issue.

**Comment by aMoniker** [comment]
I'm seeing this on OSX 10.10.4

**Comment by fiznool** [comment]
@johnmjackson what version of OS X are you running?

**Comment by johnmjackson** [comment]
Version 10.10.3 (14D136).


John Jackson, Managing Director
j <john.jackson@flgtechnology.co.uk>ohn.jackson@flgtechnology.co.uk
01282 798545

FLG Business Technology Limited is registered in England and Wales
number 5289571 at Ribble Court, 1 Mead Way, Padiham BB12 7NG.

**Comment by fiznool** [comment]
SDK now uses localtunnel instead of ngrok.

**Pull request closed without merging**
